### ISSUE TITLE
Works, but a little wonky

### ISSUE THREAD

**Issue by BlueCyro** [morganwdavis/vscode-server-freebsd#1]
Hiya. I followed this guide in an effort to get VSCode remote working on my FreeBSD install as I want to more easily do remote development on my server.

I followed this guide, but when I connect VSCode to the machine, I don't get a password prompt. Instead, I have to click `(details)` when VSCode tells me that it's installing the server, which brings me to a terminal and I have to enter the password there.

Even stranger is that this terminal never closes or drops to a prompt. I have to keep it open. To boot, any new terminals I open open with `sh` instead of `bash`, and spam "bind: not found" 6 times with a slightly broken prompt that otherwise works.

Extensions also fail to install correctly as well. They get stuck on "Installing..." when I try to install any.

I'm running FreeBSD 14.0 RELEASE, with VSCode 1.89.1 running on Windows 10.

I've also set my default shell on the FreeBSD side to bash, and even copied the `.bash_debian` file to both my user's home and the root's home, so the PATH variables are indeed functioning, albeit they seem to be concatenated with the normal PATH, which I'm not sure is correct.

Here's a printout of $PATH: `/home/cyro/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/bin/remote-cli:/compat/debian/usr/local/sbin:/compat/debian/usr/local/bin:/compat/debian/usr/sbin:/compat/debian/usr/bin:/compat/debian/sbin:/compat/debian/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by morganwdavis** [comment]
What happens if you remove `/home/cyro/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/bin/remote-cli:` from $PATH? Those server directories are transient so that path may not always exist (not that it should be necessary here anyway).

Also, do you still have trouble with VSCode 1.90.0 and the latest Remote-SSH extension?

**Comment by morganwdavis** [comment]
@BlueCyro You might want to give the new Rocky Linux emulator a try.  See the updated README.
